### ISSUE TITLE
Argument 'fn' is not a function, got string

### ISSUE THREAD

**Issue by rodoabad** [tomastrajan/angular-js-es6-testing-example#1]
Do you not get this error on your second test?

On my first test, this line will work `angular.mock.module('app');` but on my second `it` it will not and will throw that error.

**Comment by tomastrajan** [comment]
I tried both `npm test` and `npm run karma` commands and they both finished successfully. Maybe you can try deleting `node_modules` and then reinstalling it with `npm i`

**Comment by rodoabad** [comment]
For my repo. I have this setup.

``` javascript
import 'angular';
import 'angular-mocks';

import './src/client/index';

const context = require.context('./test', true, /\.spec\.js/);

context.keys()
  .forEach(context);
```

And a simple test file.

``` javascript
describe('Route: helloWorld', () => {

  let $location,
    $rootScope,
    $state,
    sandbox;

  beforeEach(angular.mock.module('app'));

  beforeEach(() => {

    sandbox = sinon.sandbox.create();

    inject((_$location_,
            _$rootScope_,
            _$state_) => {

      $location = _$location_;
      $rootScope = _$rootScope_;
      $state = _$state_;

    });

  });

  afterEach(() => {

    sandbox.restore();

  });

  it('should change the state to root.helloWorld', () => {

    const expectedState = 'root.helloWorld';

    $location.url('/helloWorld');
    $rootScope.$apply();

    expect($state.current.name)
      .to
      .equal(expectedState);

  });

  it('should change the url to "/helloWorld"', () => {

    const expectedUrl = '/helloWorld';

    $state.go('root.helloWorld');
    $rootScope.$apply();

    expect($location.url())
      .to
      .equal(expectedUrl);

  });

});
```

https://github.com/rodoabad/angularjs-unit-testing-patterns

I believe our only difference right now is that I am loading the app itself while you load the class.

I'll go ahead and try loading just the classes. I should just be stubbing the Angular services that I have dependencies on.

**Comment by rodoabad** [comment]
Finally know what's wrong @tomastrajan. If you update to 1.5.X it will fail. I downgraded my repo to 1.4.8 just like you and my tests passed.

https://github.com/rodoabad/angularjs-unit-testing-patterns/commit/06b31aff03beb5b6b4c9c55efc32811c1e8c6f63

https://travis-ci.org/rodoabad/angularjs-unit-testing-patterns/builds/93620938

Closing this now.

**Comment by tomastrajan** [comment]
Thank you for debugging that out, I will look into that and try to update my version to latest too.
