### ISSUE TITLE
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/mocha-babel

### ISSUE THREAD

**Issue by dmitriz** [tomastrajan/angular-js-es6-testing-example#2]
Sadly also problems here:

``` sh
$ npm install

...

npm ERR! Darwin 12.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/dmitrizaitsev/.npm-global/bin/npm" "i" "-d"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/mocha-babel
npm ERR! 404 
npm ERR! 404  'mocha-babel' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-js-es6-testing-example'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmitrizaitsev/Repos/angular-js-es6-testing-example/npm-debug.log
```

**Comment by tomastrajan** [comment]
Thank you, will look into that

**Comment by tomastrajan** [comment]
Ok, looks like guy removed it from NPM, check out this [issue](https://github.com/jorgetolentinog/mocha-babel/issues/5), I will migrate this one to Babel 6 for sure

**Comment by dmitriz** [comment]
What a fantastic idea :(

Is what they propose of any help:

> It is enough to run `mocha --compilers js:babel/register` instead of `mocha --compilers js:mocha-babel`

**Comment by tomastrajan** [comment]
Yes this should eventualy work, but you need add `babel-core` 6+ as dependency + compatibile `babel-loader` (for `webpack`) + `es-2015` babel preset + `.babelrc` to use the preset, will do that this evening hopefully

**Comment by tomastrajan** [comment]
Migrated to `babel6`, should work out of the box now :)

**Comment by tomastrajan** [comment]
Please, try out if it works for you

**Comment by dmitriz** [comment]
Many thanks, `webpack` runs indeed now!

And tests are passing too! Sweet. :)

Couldn't see figure how to fail karma tests though... always seem to pass ...

**Comment by tomastrajan** [comment]
You can for example change `todos.push(todo);` into `todos.push();` in `todo.service.js` this will break karma test too.

**Comment by dmitriz** [comment]
Yes, you are right, thanks, was looking in the wrong direction.
