### ISSUE TITLE
TypeError: realRunner.done is not a function

### ISSUE THREAD

**Issue by dmitriz** [tomastrajan/angular-js-es6-testing-example#3]
Not really crucial, just wanted to let you know this.

Switching features throws this in the console.
(Don't see any problem though unless I open the console.)

``` sh
TypeError: realRunner.done is not a function
    at angular-animate.js:2473
    at Scope.$digest (angular.js:15946)
    at Scope.$apply (angular.js:16160)
    at angular.js:17927
    at completeOutstandingRequest (angular.js:5552)
    at angular.js:5829
```

**Comment by tomastrajan** [comment]
Thank you, will look into that.

**Comment by tomastrajan** [comment]
So it was the beta version of `angular-animate` used `^1.4` and now works without any errors.

**Comment by alexkb** [comment]
I was seeing this error when I had Angular core 1.4.8 and angular-animate 1.4.9. After updating core to be consistent versions, the error disappeared.

**Comment by abiodun0** [comment]
@alexkb By updating the core to the consistent version. do you mean you had to update angular core to 1.4.9

**Comment by alexkb** [comment]
@abiodun0 - correct.
