### ISSUE TITLE
Add this repo to awesome angular?

### ISSUE THREAD

**Issue by dmitriz** [tomastrajan/angular-js-es6-testing-example#4]
Not an issue but suggestion to add to:

https://github.com/gianarb/awesome-angularjs

I think it this example is awesome and deserves to be there :)

**Comment by tomastrajan** [comment]
Can you submit a PR with link ?

**Comment by dmitriz** [comment]
Sure, what kind of link text, and what description?

**Comment by tomastrajan** [comment]
Link to the repository and text can be something like: [tomastrajan/angular-js-es6-testing-example](https://github.com/tomastrajan/angular-js-es6-testing-example) - Angular JS seed repository with focus on unit & integration testing (ES6, webpack, karma, mocha), suitable for serious / enterprise projects

**Comment by tomastrajan** [comment]
Thank you for your effort!

**Comment by dmitriz** [comment]
No problem, was a pleasure. :)
